### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by lxrswdd** [Vchitect/LaVie#66]
Hi  we got the following error.

```
(lavie) assa8945@ubco-csl-105751:~/video_generators/LaVie/base$ python pipelines/sample.py --config configs/sample.yaml
Traceback (most recent call last):
  File "/home/assa8945/video_generators/LaVie/base/pipelines/sample.py", line 88, in <module>
    main(OmegaConf.load(args.config))
  File "/home/assa8945/video_generators/LaVie/base/pipelines/sample.py", line 26, in main
    unet = get_models(args, sd_path).to(device, dtype=torch.float16)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/assa8945/video_generators/LaVie/base/models/__init__.py", line 30, in get_models
    return UNet3DConditionModel.from_pretrained_2d(sd_path, subfolder="unet")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/assa8945/video_generators/LaVie/base/models/unet.py", line 574, in from_pretrained_2d
    state_dict = torch.load(model_file, map_location="cpu")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/assa8945/miniconda3/envs/lavie/lib/python3.11/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/assa8945/miniconda3/envs/lavie/lib/python3.11/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by jetamie** [comment]
明显模型下载的不完整

**Comment by LZVSDY** [comment]
```
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
apt-get install git-lfs
git lfs install
git lfs clone https://huggingface.co/xxxxxxx # accroding to u
```
maybe it's work for U
